services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  celery-worker-1:
    image: celery-worker:latest
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    command:  ["celery", "--app=tasks", "worker", "-l", "INFO"]
    healthcheck:
      test: [ "CMD", "celery", "-A", "tasks", "inspect", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  celery-worker-2:
    image: celery-worker:latest
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    command:  ["celery", "--app=tasks", "worker", "-l", "INFO"]
    healthcheck:
      test: [ "CMD", "celery", "-A", "tasks", "inspect", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s